#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER n8n WITH PASSWORD 'n8n';
    CREATE DATABASE n8n;
    GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n;
EOSQL

